### ISSUE TITLE
[JOSS #2708] Adding missing DOIs in paper.bib

### ISSUE THREAD

**Issue by kakiac** [jongheepark/NetworkChange#17]
Our bot Whedon has reported that the following papers/citations have missing dois - could you please have a look and see if they are correct and add them to your paper.bib file.

- 10.18637/jss.v024.i05 may be a valid DOI for title: Fitting position latent cluster models for social networks with latentnet
- 10.1214/19-ba1147 may be a valid DOI for title: Detecting Structural Changes in Longitudinal Network Data
- 10.1214/15-aoas839 may be a valid DOI for title: Multilinear tensor regression for longitudinal relational data
- 10.21236/ada458734 may be a valid DOI for title: Latent space approaches to social network analysis

Also worth checking the rest of the references if they do not have a doi, in case there is one you can add.

Thanks 👍

**Comment by ysohn** [comment]
We have updated paper.bib by including publisher dois of the papers.
