### ISSUE TITLE
No example to demonstrate fitting with covariates

### ISSUE THREAD

**Issue by martinmodrak** [jongheepark/NetworkChange#5]
Based on the description in the Bayesian analysis paper, fitting models with covariates should be supported. It is however unclear how one should do that as the `NetworkChange` function has parameters only for response and priors, not for predictors. The vignette or other documentation should show how to do this, or - if this is not currently possible (which is OK), then I don't understand what the prior for β  (parameters `b0` and `B0`) is for.

**Comment by ysohn** [comment]
If the user does not set constant = TRUE, which draws intercept samples, the B0 and b0 parameters are not used in MCMC sampling. The parameters B0 and b0 are included in the code for internal testing and future use.
