### ISSUE TITLE
[JOSS #2708] Expand paper

### ISSUE THREAD

**Issue by kakiac** [jongheepark/NetworkChange#7]
(copying comments from https://github.com/openjournals/joss-reviews/issues/2708 )

Overall your paper is quite short. Although JOSS papers are generally only one or two pages on average (250-1000 words), your paper just barely passes that mark. I would recommend adding a bit more content, perhaps an example or more explanation/details of how the package works. Consider adding elements from this page: https://cran.r-project.org/web/packages/NetworkChange/vignettes/NetworkChange.html

**Comment by kakiac** [comment]
You might also consider adding something along the lines of from @akbaritabar's comment (https://github.com/openjournals/joss-reviews/issues/2708#issuecomment-719592111)

> A bit more description about the empirical network data used would be nice (e.g., I found this in the 2020 paper by the authors in Bayesian Analysis journal which made it much clearer for me (quoting this from that paper's text) "The structure of military alliance networks reflects the distribution of military power among coalitions of states, which changes over time in response to exogenous shocks to the international system or endogenous network dynamics. However, there has been no study that investigates changes in coalition structures of military alliance networks over time using a principled statistical approach. A main reason is the lack of statistical methods that model unknown structural changes in longitudinal network data.").

**Comment by kakiac** [comment]
You might also consider improving/adding a few sentences to help a non-specialist audience understand what this package does and how it fits with other packages both in the readme.md of your repository and your paper. See also @akbaritabar 's comment here https://github.com/openjournals/joss-reviews/issues/2708#issuecomment-719592111:

> The current description can be further improved. For example, for me as someone who knows about network analysis, block-modeling, community detection and similar techniques, I cannot say the whole methodology and descriptions are clear but that could be my lack of enough background knowledge.

**Comment by ysohn** [comment]
We have expanded the paper by reflecting the reviewers and the editor's comments.
