### ISSUE TITLE
[JOSS #2708] R Object Conversion to NetworkChange & Usage

### ISSUE THREAD

**Issue by kakiac** [jongheepark/NetworkChange#9]
Comment from @akbaritabar from https://github.com/openjournals/joss-reviews/issues/2708#issuecomment-719592111:

@ysohn this would be another area to consider including some information on that would both make the paper more self contained and will also help address the EiC's comments on expanding it a bit!

Let me know what you think 💭 

> An example of how objects from popular R libraries for network analysis (e.g., igraph and statnet suite) or external formats (e.g., Pajek plain text format) can be converted and used with NetworkChange will be really helpful. At first it feels like array of temporal snapshots is easy to build, but it might not be for all potential users. I took the time to test it on a fake co-authorship network and it was not as straightforward as I hoped it would be (please see above in first paragraph that I am an advanced beginner and it might only be my problem). I used a bipartite edgelist saved in CSV including source/target columns for authors and publication nodes and a publication year column (see below for the example). I constructed a bipartite graph with igraph, then induced yearly subgraphs (to have temporal dimension to explore with NetworkChange) and then projected them to one-mode (authors). I then used array from R to get close to the MajourAlly shape, but I failed and couldn't understand how I need to provide the dimensions to then use NetworkChange on the sample. Providing a bit of description on this would allow the package to be used by a wider range of audience.

> This is example of bipartite ties I tried to convert and used and failed in the latest step:

```
# example data (edges table) in csv format to copy/paste

source,target,PUBYEAR
author_1,paper_2,2007
author_2,paper_2,2007
author_3,paper_2,2007
author_4,paper_2,2007
author_5,paper_2,2007
author_1,paper_3,2011
author_2,paper_3,2011
author_3,paper_3,2011
author_4,paper_3,2011
author_5,paper_3,2011
author_1,paper_4,2012
author_2,paper_4,2012
author_3,paper_4,2012
author_4,paper_4,2012
author_5,paper_4,2012
author_1,paper_1,2013
author_2,paper_1,2013
author_3,paper_1,2013
author_4,paper_1,2013
author_5,paper_1,2013


# example data (vertices table) in csv format to copy/paste

vertices,type
author_1,TRUE
author_2,TRUE
author_3,TRUE
author_4,TRUE
author_5,TRUE
paper_1,FALSE
paper_2,FALSE
paper_3,FALSE
paper_4,FALSE


# Preparing to use with NetworkChange
require(tidyverse)
require(igraph)

edges_table <- read_csv('./edges.csv') %>% 
  arrange(PUBYEAR)

vertices_table <- read_csv('./vertices.csv')

# build a bipartite paper-author graph
g <- graph_from_data_frame(d = edges_table, vertices = vertices_table, directed = F)

yearly_g <- list()
for (year in unique(edges_table$PUBYEAR)) {
  # delete.vertices = FALSE because we need same dim for all matrices
  g_year <- subgraph.edges(g, E(g)[PUBYEAR == year], delete.vertices = FALSE)
  g_aut <- bipartite.projection(g_year, which = 'true')
  g_adj <- as.matrix(get.adjacency(g_aut, edges = F, names = T))
  yearly_g[[paste0('y_', as.character(year))]] <- g_adj
}

# Here I am not sure how to give the right dimensions and fail in building the right array that NetworkChange will use
arr_yearly_g <- array(yearly_g)

### the error I get is like this:

# use networkchange
G <- 100
set.seed(1990)
test.run <- NetworkStatic(arr_yearly_g, R=2, mcmc=G, burnin=G, verbose=0,
                          v0=10, v1=4*2)

# Error in array(Y, dim = c(dim(Y)[1], dim(Y)[2], 1)) : 
#   negative length vectors are not allowed 

```

**Comment by ysohn** [comment]
The following is included in the paper. 

> The input network data for **NetworkChange** is a full three-dimensional array with dimensions $N$ by $N$ by $T$, where $N$ is the number of nodes and $T$ is the number of observed time points, and each slice represents an adjacency matrix for a specific time point. Most other network packages include a function for converting an edge list or other sparse representation of network data into an adjacency matrix format. For example, the **igraph** package includes the `as.matrix.igraph` function, and the **sna** package includes the `as.sociomatrix.sna` function.

> The method provides estimation of a one mode (i.e. unipartite) symmetric (i.e. undirected) longitudinal network data. In order to analyze a bipartite network data set, users may apply one-mode projection of each cross-sectional network to obtain a symmetric matrix for a node set which belongs to one of the two modes.
